# Generated by Django 5.1.3 on 2026-04-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_merchan_68130b_idx',
            old_name='ledger_entr_merchan_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_merchan_2b8c6e_idx',
            old_name='ledger_entr_merchan_d4e5f6_idx',
        ),
    ]
