# Generated by Django 5.1.3 on 2026-04-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='idempotency_expires_6c9d28_idx',
            old_name='idempotenc_expires_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_merchan_a5cc5c_idx',
            old_name='payouts_merchan_b1234a_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_status_726895_idx',
            old_name='payouts_status_b9c1d2_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_merchan_44832a_idx',
            old_name='payouts_merchan_3d4e5f_idx',
        ),
    ]
