# Generated by Django 5.1.3 on 2026-04-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bank_accoun_merchan_28413e_idx',
            old_name='bank_accoun_merchan_b8f0d2_idx',
        ),
    ]
